# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import capping_pb2 as capping__pb2


class CappingStub(object):
    """Interface exported by the server.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Cap = channel.unary_unary(
                '/capping.Capping/Cap',
                request_serializer=capping__pb2.CapInput.SerializeToString,
                response_deserializer=capping__pb2.CapResult.FromString,
                )


class CappingServicer(object):
    """Interface exported by the server.

    """

    def Cap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CappingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Cap': grpc.unary_unary_rpc_method_handler(
                    servicer.Cap,
                    request_deserializer=capping__pb2.CapInput.FromString,
                    response_serializer=capping__pb2.CapResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'capping.Capping', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Capping(object):
    """Interface exported by the server.

    """

    @staticmethod
    def Cap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/capping.Capping/Cap',
            capping__pb2.CapInput.SerializeToString,
            capping__pb2.CapResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
